config/routes.rb
Hotel::Application.routes.draw do
  
  root :to => 'pages#index'

  match '/reservas/confirma/:id' => 'reservas#confirma', :as => :confirma_reserva
  match 'admin/' => 'admin/dashboard#index', :as => :admin_home
  match '/reservas/show/:dataEntrada/:dataSaida' => 'reservas#show'
  match '/reservas/create' => 'reservas#create', :as => :create_reserva
  match '/reservas/nova/:id/:dataEntrada/:dataSaida' => 'reservas#nova', :as => :nova_reserva
  match '/clientes/sucesso' => 'clientes#sucesso', :as => :cliente_sucesso

  resources :quartos

  namespace :admin do
    resources :produtos
    resources :checkouts do
      member do
        get :imprimir
      end
    end
    resources :clientes
    resources :usuarios
    resources :flags
    resources :quartos
    resources :tipos_quartos
    resources :reservas do 
      member do
        get :checkout
        post :checkout_save
      end
    end
    
  end
  
  devise_for :usuarios, :skip => [:sessions], :controllers => { :sessions => "admin/sessions"}
  
  as :usuario do
    get 'admin/login' => 'admin/sessions#new', :as => :new_usuario_session
    post 'admin/login' => 'admin/sessions#create', :as => :usuario_session
    get 'admin/logout' => 'admin/sessions#destroy', :as => :destroy_usuario_session,
    :via => Devise.mappings[:usuario].sign_out_via
  end

  devise_for :clientes, :controllers => { :sessions => "sessions", :registrations => :registrations}
  
  as :cliente do
    get 'clientes/login' => 'sessions#new', :as => :new_cliente_session
    post 'clientes/login' => 'sessions#create', :as => :cliente_session
    get 'clientes/logout' => 'sessions#destroy', :as => :destroy_cliente_session,
    :via => Devise.mappings[:cliente].sign_out_via
  end
  
  match ':controller(/:action(/:id))(.:format)'
  

  
end

app/models/reserva.rb
class ReservaValidate < ActiveModel::Validator
  def validate(record)
    if record.DataEntrada > record.DataSaida
      record.errors[:DataEntrada] << "deve ser menor que a data de Saida"
      record.errors[:DataSaida] << "deve ser maior que a data de Entrada"
    end
  end
end

class Reserva < ActiveRecord::Base
  
  belongs_to :Cliente
  
  belongs_to :Quarto
  
  has_one :Checkout
  
  validates_with ReservaValidate
  
  validates_associated :Cliente, :Quarto
  
  attr_accessible :DataEntrada, :DataPagamento, :DataSaida, :Pagamento, :Cliente_id, :Quarto_id, :Quarto
  
  validates_presence_of :Cliente_id, :DataEntrada, :DataSaida
  
  def diarias
    diarias = self.DataEntrada.time.hour < 12 ? 1 : 0
    diarias = diarias + (self.DataSaida.to_date - self.DataEntrada.to_date).to_i
    diarias = self.DataSaida.time.hour > 12 ? diarias + 1 : diarias
    diarias
  end
  
  def valor_diarias
    diarias = self.diarias
    valor = self.Quarto.diaria * diarias
    valor
  end
  
end

app/controllers/admin/reservas_controller.rb
class Admin::ReservasController < Admin::ApplicationController
  # GET /reservas
  # GET /reservas.json
  def index
    @reservas = Reserva.find(:all, :include => :Checkout, :conditions => { :checkouts => {:id => nil}} )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservas }
    end
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show
    @reserva = Reserva.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reserva }
    end
  end

  # GET /reservas/new
  # GET /reservas/new.json
  def new
    @reserva = Reserva.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reserva }
    end
  end

  # GET /reservas/1/edit
  def edit
    @reserva = Reserva.find(params[:id])
  end

  # POST /reservas
  # POST /reservas.json
  def create
    @reserva = Reserva.new(params[:reserva])

    respond_to do |format|
      if @reserva.save
        format.html { redirect_to [:admin, @reserva], notice: 'Reserva adicionada com sucesso.' }
        format.json { render json: @reserva, status: :created, location: @reserva }
      else
        format.html { render action: "new" }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservas/1
  # PUT /reservas/1.json
  def update
    @reserva = Reserva.find(params[:id])

    respond_to do |format|
      if @reserva.update_attributes(params[:reserva])
        format.html { redirect_to [:admin, @reserva], notice: 'Reserva atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva = Reserva.find(params[:id])
    @reserva.destroy

    respond_to do |format|
      format.html { redirect_to admin_reservas_url }
      format.json { head :no_content }
    end
  end


  # GET /reservas/1/checkout
  def checkout
    @reserva = Reserva.find(params[:id])

    respond_to do |format|
      format.html # checkout.html.erb
    end
  end

  # PUT /reservas/1/checkout_save
  def checkout_save

    @reserva = Reserva.find(params[:id])
    @reserva.Checkout = Checkout.new(params[:checkout])
    
    @reserva.DataSaida = DateTime.now
    
    consumos = []
    params[:consumo].each do |v,c|
      consumos.push Consumo.new(c)
    end
    @reserva.Checkout.Consumo = consumos
    
    respond_to do |format|
      if @reserva.save
        format.html { redirect_to [:admin, @reserva.Checkout], notice: 'Checkout efetuado com sucesso!' }
        format.json { render json: @reserva.Checkout, status: :created, location: @reserva.Checkout }
      else
        format.html { render action: "checkout_save" }
        format.json { render json: @reserva.Checkout.errors, status: :unprocessable_entity }
      end
    end
  end
  
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  
  before_filter :authenticate_cliente!, :only => [:nova, :create, :sucesso]

  def after_sign_in_path_for(resource)
    Rails.application.routes.url_helpers.cliente_sucesso_path
  end
  
  # GET /reservas/show/:dataEntrada/:dataSaida
  def show    
    @quartos = Quarto.all
    @quartos_livres = [];
    
    @quartos.each do |quarto|
      if !quarto.ocupado? params[:dataEntrada].to_datetime, params[:dataSaida].to_datetime
        @quartos_livres.push quarto
      end
    end
    
  end
  
  # GET /reservas/nova/:id/:dataEntrada/:dataSaida
  def nova
    @quarto = Quarto.find(params[:id])
    
    @reserva = Reserva.new({
      :DataEntrada => params[:dataEntrada].to_datetime,
      :DataSaida => params[:dataSaida].to_datetime,
      :Quarto_id => @quarto.id
      })
    
    end
  
    # POST /reservas
    # POST /reservas.json
    def create
      @reserva = Reserva.new(params[:reserva])
      @reserva.Cliente = current_cliente

      respond_to do |format|
        if @reserva.save
          format.html { redirect_to :action => "pagamento", :id => @reserva.id }
          format.json { render json: @reserva, status: :created, location: @reserva }
        else
          format.html { render json: @reserva.errors, notice: 'Ocorreu algum erro ao salvar esta reserva.' }
          format.json { render json: @reserva.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def confirma
      @reserva = Reserva.find(params[:id])
            
      if @reserva.Pagamento == nil
        @reserva.Pagamento = "50% pagos"
      end
      
      respond_to do |format|
        if @reserva.save
          
          DefaultMailer.confirma_reserva(@reserva).deliver
          
          format.html { render :layout => "login" }
          format.json { render json: @reserva, status: :created, location: @reserva }
        else
          format.html { render json: @reserva.errors, notice: 'Ocorreu algum erro ao salvar esta reserva.' }
          format.json { render json: @reserva.errors, status: :unprocessable_entity }
        end
      end
      
    end
    
    def pagamento
      @reserva = Reserva.find(params[:id])
      
      render :layout => "login"
    end
  
  end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/reservas/cadastro_sucesso.erb
<div id="outer-wrapper">

	<div id="top-wrapper">
		<div class="container">
			<div id="top">
				<div id="logo">
					<a href="/"><img src="/images/logo.gif" alt=""></a>
				</div><!-- #logo -->
				<div id="mainmenu">
					<ul class="sn">
						<li><a href="#"><img src="/images/icon/i-facebook.png" alt=""></a></li>
						<li><a href="#"><img src="/images/icon/i-last.fm.png" alt=""></a></li>
						<li><a href="#"><img src="/images/icon/i-myspace.png" alt=""></a></li>
						<li><a href="#"><img src="/images/icon/i-twitter.png" alt=""></a></li>
						<li><a href="#"><img src="/images/icon/i-youtube.png" alt=""></a></li>
					</ul>

					<ul id="menu">
						<li class="current"><a href="/">Home</a></li>
						<li><a href="#">Sobre</a>
							<ul style="visibility: hidden;">
								<li><a href="#">Institucional</a></li>
								<li><a href="#">Blog</a></li>
							</ul>
						</li>
						<li><a href="#">Serviços</a></li>
						<li><a href="#">Quartos</a></li>
						<li><a href="#">Reserva</a></li>
						<li><a href="#">Fotos</a></li>
						<li><a href="#">Contato</a></li>
					</ul>
					<div class="clear"></div>
				</div><!-- #mainmenu -->
			</div><!-- #top -->
           
		</div><!-- .container -->
	</div><!-- #top-wrapper -->
    

	<div id="header-container">
		<img src="/images/pic-inner5.jpg" alt="">
	</div><!-- #header-container -->
	<div class="clear"></div>
    
	<div id="content-wrapper" class="inner">
		<div class="container">
			<div id="content-container">
				<div id="frame-content-t">
					<div id="frame-content-b">
 
						<div class="center">
							<div id="main-content" class="full">

								<br/><br/><br/><br/><br/><br/><br/><br/>
								<h1><center>Obrigado!<br/>Sua reserva efetuada com sucesso!</center></h1>
								<br/><br/><br/><br/><br/><br/><br/><br/>
								
								</div><!-- #main-content -->
                        
								<div class="clear"></div>
							</div><!-- .center -->
                
							<div class="clear"></div>
						</div><!-- #frame-content-b -->
					</div><!-- #frame-content-t -->
				</div><!-- #content-container -->
			</div><!-- .container -->
		</div><!-- #content-wrapper -->

		<div id="footer-wrapper">
			<div class="container">
				<div id="footer">
					<ul id="footer-menu">
						<li><a href="/">Home</a></li>
						<li><a href="#">Sobre</a></li>
						<li><a href="#">Serviços</a></li>
						<li><a href="#">Quartos</a></li>
						<li><a href="#">Reserva</a></li>
						<li><a href="#">Fotos</a></li>
						<li><a href="#">Contato</a></li>
					</ul>
					<div id="copyright">Copyright ©2012 Classica Hotel. All Rights Reserved</div>
				</div><!-- #footer -->
			</div><!-- .container -->
		</div><!-- #footer-wrapper -->
	</div>

	<script type="text/javascript"> Cufon.now(); </script> <!-- to fix cufon problems in IE browser -->
	<script type="text/javascript">jQuery('#noscript').remove();</script><!-- if javascript disable -->

app/views/reservas/confirma.erb
<center>
	<h2>Obrigado, sua reserva foi efetuada com sucesso!</h2>
</center>

app/views/reservas/nova.html.erb
<div id="outer-wrapper">

	<div id="top-wrapper">
		<div class="container">
			<div id="top">
				<div id="logo">
					<a href="/"><img src="/images/logo.gif" alt=""></a>
				</div><!-- #logo -->
				<div id="mainmenu">
					<ul class="sn">
						<li><a href="#"><img src="/images/icon/i-facebook.png" alt=""></a></li>
						<li><a href="#"><img src="/images/icon/i-last.fm.png" alt=""></a></li>
						<li><a href="#"><img src="/images/icon/i-myspace.png" alt=""></a></li>
						<li><a href="#"><img src="/images/icon/i-twitter.png" alt=""></a></li>
						<li><a href="#"><img src="/images/icon/i-youtube.png" alt=""></a></li>
					</ul>

					<ul id="menu">
						<li class="current"><a href="/">Home</a></li>
						<li><a href="#">Sobre</a>
							<ul style="visibility: hidden;">
								<li><a href="#">Institucional</a></li>
								<li><a href="#">Blog</a></li>
							</ul>
						</li>
						<li><a href="#">Serviços</a></li>
						<li><a href="#">Quartos</a></li>
						<li><a href="#">Reserva</a></li>
						<li><a href="#">Fotos</a></li>
						<li><a href="#">Contato</a></li>
					</ul>
					<div class="clear"></div>
				</div><!-- #mainmenu -->
			</div><!-- #top -->
           
		</div><!-- .container -->
	</div><!-- #top-wrapper -->
    

	<div id="header-container">
		<img src="/images/pic-inner5.jpg" alt="">
	</div><!-- #header-container -->
	<div class="clear"></div>
    
	<div id="content-wrapper" class="inner">
		<div class="container">
			<div id="content-container">
				<div id="frame-content-t">
					<div id="frame-content-b">
 
						<div class="center">
							<div id="main-content" class="full">
								<h1>Quarto <%= @quarto.nome %>:</h1>
								
								<h3>Dados do Cliente:</h3>
								
								<p>
									<b>Nome:</b> <%= current_cliente.nome_completo %><br/>
									<b>Endereço:</b> <%= current_cliente.rua %>, <%= current_cliente.numero %>/<%= current_cliente.complemento %> - <%= current_cliente.bairro %> - <%= current_cliente.cidade %>/<%= current_cliente.estado %> <br/>
									<b>Telefones:</b> <%= current_cliente.telefone %>, <%= current_cliente.celular %> <br/>
								</p>
								
								<h3>Dados da Reserva:</h3>
								
								<p>
									<b>Data de Entrada:</b> <%=l params[:dataEntrada].to_datetime %><br/>
									<b>Data de Saida:</b> <%=l params[:dataSaida].to_datetime %><br/>
									<b>Valor da Diaria:</b> <%= @quarto.diaria.real_formatado %><br/>
									<b>Quantidade de Diarias:</b> <%= @reserva.diarias %><br/>
								</p>
								<p>
									<b>Valor Total da Reserva:</b> <%= @reserva.valor_diarias.real_formatado %> <br/>
								</p>
                <%= form_for @reserva, :url => :create_reserva, :html => { :class => 'form-horizontal' } do |f| %>
								
								<%= f.hidden_field :DataEntrada, :value => params[:dataEntrada] %>
								<%= f.hidden_field :DataSaida, :value => params[:dataSaida] %>
								<%= f.hidden_field :DataPagamento, :value => DateTime.now %>
								<%= f.hidden_field :Quarto_id, :value => @quarto.id %>
													 
								<input type="submit" value="Confirmar Reserva"/>
								
								<% end %>
								
								</div><!-- #main-content -->
                        
								<div class="clear"></div>
							</div><!-- .center -->
                
							<div class="clear"></div>
						</div><!-- #frame-content-b -->
					</div><!-- #frame-content-t -->
				</div><!-- #content-container -->
			</div><!-- .container -->
		</div><!-- #content-wrapper -->

		<div id="footer-wrapper">
			<div class="container">
				<div id="footer">
					<ul id="footer-menu">
						<li><a href="/">Home</a></li>
						<li><a href="#">Sobre</a></li>
						<li><a href="#">Serviços</a></li>
						<li><a href="#">Quartos</a></li>
						<li><a href="#">Reserva</a></li>
						<li><a href="#">Fotos</a></li>
						<li><a href="#">Contato</a></li>
					</ul>
					<div id="copyright">Copyright ©2012 Classica Hotel. All Rights Reserved</div>
				</div><!-- #footer -->
			</div><!-- .container -->
		</div><!-- #footer-wrapper -->
	</div>

	<script type="text/javascript"> Cufon.now(); </script> <!-- to fix cufon problems in IE browser -->
	<script type="text/javascript">jQuery('#noscript').remove();</script><!-- if javascript disable -->

app/views/reservas/pagamento.erb
<center>
	<h2>Para sua reserva ser concluida voce deve pagar 50% do valor.</h2>
	<h3>No total de <%= (@reserva.valor_diarias/2).real_formatado %></h3>
	
	<%= link_to "Efetuar Pagamento", confirma_reserva_path(@reserva) %>
</center>

app/views/reservas/show.html.erb
<div id="outer-wrapper">

	<div id="top-wrapper">
		<div class="container">
			<div id="top">
				<div id="logo">
					<a href="/"><img src="/images/logo.gif" alt=""></a>
				</div><!-- #logo -->
				<div id="mainmenu">
					<ul class="sn">
						<li><a href="#"><img src="/images/icon/i-facebook.png" alt=""></a></li>
						<li><a href="#"><img src="/images/icon/i-last.fm.png" alt=""></a></li>
						<li><a href="#"><img src="/images/icon/i-myspace.png" alt=""></a></li>
						<li><a href="#"><img src="/images/icon/i-twitter.png" alt=""></a></li>
						<li><a href="#"><img src="/images/icon/i-youtube.png" alt=""></a></li>
					</ul>

					<ul id="menu">
						<li class="current"><a href="/">Home</a></li>
						<li><a href="#">Sobre</a>
							<ul style="visibility: hidden;">
								<li><a href="#">Institucional</a></li>
								<li><a href="#">Blog</a></li>
							</ul>
						</li>
						<li><a href="#">Serviços</a></li>
						<li><a href="#">Quartos</a></li>
						<li><a href="#">Reserva</a></li>
						<li><a href="#">Fotos</a></li>
						<li><a href="#">Contato</a></li>
					</ul>
					<div class="clear"></div>
				</div><!-- #mainmenu -->
			</div><!-- #top -->
           
		</div><!-- .container -->
	</div><!-- #top-wrapper -->
    

	<div id="header-container">
		<img src="/images/pic-inner5.jpg" alt="">
	</div><!-- #header-container -->
	<div class="clear"></div>
    
	<div id="content-wrapper" class="inner">
		<div class="container">
			<div id="content-container">
				<div id="frame-content-t">
					<div id="frame-content-b">
 
						<div class="center">
							<div id="main-content" class="full">
								<h1>Quartos:</h1>
								<% if @quartos_livres.size > 0 %>
								<p>Abaixo estão os quartos disponíveis no período de <b><%=l params[:dataEntrada].to_datetime %></b> á <b><%=l params[:dataSaida].to_datetime %></b>.</p>
								<p>Clique sobre, para fazer a reserva:</p>
								<div class="quartos">
									<% @quartos_livres.each do |quarto| %>
									<div class="quarto">
										<div class="bg"></div>
										<div class="id">COD: <%= quarto.id %></div>
										<div class="tipo"><%= quarto.tipos_quarto.nome %></div>
										<div class="diaria"><%= quarto.diaria.reais_formatado %></div>
										<div class="flags">
											<% for flag in Flag.find(:all) %> 
											<%= quarto.flags.include?(flag) ? flag.nome : nil %>
											<%= quarto.flags.include?(flag) && flag != quarto.flags.last ? ', ' : nil %>
											<% end %>
										</div>
										<%= image_tag(quarto.imagem.url(:medium)) %>
									</div>
									<% end %>

									<% elsif %>
								<p>Não temos quartos disponíveis no período de <b><%=l params[:dataEntrada].to_datetime %></b> á <b><%=l params[:dataSaida].to_datetime %></b>.</p>
									<% end %>
								</div>
                           
								</div><!-- #main-content -->
                        
								<div class="clear"></div>
							</div><!-- .center -->
                
							<div class="clear"></div>
						</div><!-- #frame-content-b -->
					</div><!-- #frame-content-t -->
				</div><!-- #content-container -->
			</div><!-- .container -->
		</div><!-- #content-wrapper -->

		<div id="footer-wrapper">
			<div class="container">
				<div id="footer">
					<ul id="footer-menu">
						<li><a href="/">Home</a></li>
						<li><a href="#">Sobre</a></li>
						<li><a href="#">Serviços</a></li>
						<li><a href="#">Quartos</a></li>
						<li><a href="#">Reserva</a></li>
						<li><a href="#">Fotos</a></li>
						<li><a href="#">Contato</a></li>
					</ul>
					<div id="copyright">Copyright ©2012 Classica Hotel. All Rights Reserved</div>
				</div><!-- #footer -->
			</div><!-- .container -->
		</div><!-- #footer-wrapper -->
	</div>

	<script type="text/javascript"> Cufon.now(); </script> <!-- to fix cufon problems in IE browser -->
	<script type="text/javascript">jQuery('#noscript').remove();</script><!-- if javascript disable -->

app/views/reservas/sucesso.html.erb
<div id="outer-wrapper">

	<div id="top-wrapper">
		<div class="container">
			<div id="top">
				<div id="logo">
					<a href="/"><img src="/images/logo.gif" alt=""></a>
				</div><!-- #logo -->
				<div id="mainmenu">
					<ul class="sn">
						<li><a href="#"><img src="/images/icon/i-facebook.png" alt=""></a></li>
						<li><a href="#"><img src="/images/icon/i-last.fm.png" alt=""></a></li>
						<li><a href="#"><img src="/images/icon/i-myspace.png" alt=""></a></li>
						<li><a href="#"><img src="/images/icon/i-twitter.png" alt=""></a></li>
						<li><a href="#"><img src="/images/icon/i-youtube.png" alt=""></a></li>
					</ul>

					<ul id="menu">
						<li class="current"><a href="/">Home</a></li>
						<li><a href="#">Sobre</a>
							<ul style="visibility: hidden;">
								<li><a href="#">Institucional</a></li>
								<li><a href="#">Blog</a></li>
							</ul>
						</li>
						<li><a href="#">Serviços</a></li>
						<li><a href="#">Quartos</a></li>
						<li><a href="#">Reserva</a></li>
						<li><a href="#">Fotos</a></li>
						<li><a href="#">Contato</a></li>
					</ul>
					<div class="clear"></div>
				</div><!-- #mainmenu -->
			</div><!-- #top -->
           
		</div><!-- .container -->
	</div><!-- #top-wrapper -->
    

	<div id="header-container">
		<img src="/images/pic-inner5.jpg" alt="">
	</div><!-- #header-container -->
	<div class="clear"></div>
    
	<div id="content-wrapper" class="inner">
		<div class="container">
			<div id="content-container">
				<div id="frame-content-t">
					<div id="frame-content-b">
 
						<div class="center">
							<div id="main-content" class="full">

								<br/><br/><br/><br/><br/><br/><br/><br/>
								<h1><center>Obrigado!<br/>Sua reserva efetuada com sucesso!</center></h1>
								<br/><br/><br/><br/><br/><br/><br/><br/>
								
								</div><!-- #main-content -->
                        
								<div class="clear"></div>
							</div><!-- .center -->
                
							<div class="clear"></div>
						</div><!-- #frame-content-b -->
					</div><!-- #frame-content-t -->
				</div><!-- #content-container -->
			</div><!-- .container -->
		</div><!-- #content-wrapper -->

		<div id="footer-wrapper">
			<div class="container">
				<div id="footer">
					<ul id="footer-menu">
						<li><a href="/">Home</a></li>
						<li><a href="#">Sobre</a></li>
						<li><a href="#">Serviços</a></li>
						<li><a href="#">Quartos</a></li>
						<li><a href="#">Reserva</a></li>
						<li><a href="#">Fotos</a></li>
						<li><a href="#">Contato</a></li>
					</ul>
					<div id="copyright">Copyright ©2012 Classica Hotel. All Rights Reserved</div>
				</div><!-- #footer -->
			</div><!-- .container -->
		</div><!-- #footer-wrapper -->
	</div>

	<script type="text/javascript"> Cufon.now(); </script> <!-- to fix cufon problems in IE browser -->
	<script type="text/javascript">jQuery('#noscript').remove();</script><!-- if javascript disable -->