config/routes.rb
Hotel::Application.routes.draw do
  
  root :to => 'pages#index'

  match '/reservas/confirma/:id' => 'reservas#confirma', :as => :confirma_reserva
  match 'admin/' => 'admin/dashboard#index', :as => :admin_home
  match '/reservas/show/:dataEntrada/:dataSaida' => 'reservas#show'
  match '/reservas/create' => 'reservas#create', :as => :create_reserva
  match '/reservas/nova/:id/:dataEntrada/:dataSaida' => 'reservas#nova', :as => :nova_reserva
  match '/clientes/sucesso' => 'clientes#sucesso', :as => :cliente_sucesso

  resources :quartos

  namespace :admin do
    resources :produtos
    resources :checkouts do
      member do
        get :imprimir
      end
    end
    resources :clientes
    resources :usuarios
    resources :flags
    resources :quartos
    resources :tipos_quartos
    resources :reservas do 
      member do
        get :checkout
        post :checkout_save
      end
    end
    
  end
  
  devise_for :usuarios, :skip => [:sessions], :controllers => { :sessions => "admin/sessions"}
  
  as :usuario do
    get 'admin/login' => 'admin/sessions#new', :as => :new_usuario_session
    post 'admin/login' => 'admin/sessions#create', :as => :usuario_session
    get 'admin/logout' => 'admin/sessions#destroy', :as => :destroy_usuario_session,
    :via => Devise.mappings[:usuario].sign_out_via
  end

  devise_for :clientes, :controllers => { :sessions => "sessions", :registrations => :registrations}
  
  as :cliente do
    get 'clientes/login' => 'sessions#new', :as => :new_cliente_session
    post 'clientes/login' => 'sessions#create', :as => :cliente_session
    get 'clientes/logout' => 'sessions#destroy', :as => :destroy_cliente_session,
    :via => Devise.mappings[:cliente].sign_out_via
  end
  
  match ':controller(/:action(/:id))(.:format)'
  

  
end

app/models/reserva.rb
class ReservaValidate < ActiveModel::Validator
  def validate(record)
    if record.DataEntrada > record.DataSaida
      record.errors[:DataEntrada] << "deve ser menor que a data de Saida"
      record.errors[:DataSaida] << "deve ser maior que a data de Entrada"
    end
  end
end

class Reserva < ActiveRecord::Base
  
  belongs_to :Cliente
  
  belongs_to :Quarto
  
  has_one :Checkout
  
  validates_with ReservaValidate
  
  validates_associated :Cliente, :Quarto
  
  attr_accessible :DataEntrada, :DataPagamento, :DataSaida, :Pagamento, :Cliente_id, :Quarto_id, :Quarto
  
  validates_presence_of :Cliente_id, :DataEntrada, :DataSaida
  
  def diarias
    diarias = self.DataEntrada.time.hour < 12 ? 1 : 0
    diarias = diarias + (self.DataSaida.to_date - self.DataEntrada.to_date).to_i
    diarias = self.DataSaida.time.hour > 12 ? diarias + 1 : diarias
    diarias
  end
  
  def valor_diarias
    diarias = self.diarias
    valor = self.Quarto.diaria * diarias
    valor
  end
  
end

app/controllers/admin/reservas_controller.rb
class Admin::ReservasController < Admin::ApplicationController
  # GET /reservas
  # GET /reservas.json
  def index
    @reservas = Reserva.find(:all, :include => :Checkout, :conditions => { :checkouts => {:id => nil}} )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservas }
    end
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show
    @reserva = Reserva.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reserva }
    end
  end

  # GET /reservas/new
  # GET /reservas/new.json
  def new
    @reserva = Reserva.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reserva }
    end
  end

  # GET /reservas/1/edit
  def edit
    @reserva = Reserva.find(params[:id])
  end

  # POST /reservas
  # POST /reservas.json
  def create
    @reserva = Reserva.new(params[:reserva])

    respond_to do |format|
      if @reserva.save
        format.html { redirect_to [:admin, @reserva], notice: 'Reserva adicionada com sucesso.' }
        format.json { render json: @reserva, status: :created, location: @reserva }
      else
        format.html { render action: "new" }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservas/1
  # PUT /reservas/1.json
  def update
    @reserva = Reserva.find(params[:id])

    respond_to do |format|
      if @reserva.update_attributes(params[:reserva])
        format.html { redirect_to [:admin, @reserva], notice: 'Reserva atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva = Reserva.find(params[:id])
    @reserva.destroy

    respond_to do |format|
      format.html { redirect_to admin_reservas_url }
      format.json { head :no_content }
    end
  end


  # GET /reservas/1/checkout
  def checkout
    @reserva = Reserva.find(params[:id])

    respond_to do |format|
      format.html # checkout.html.erb
    end
  end

  # PUT /reservas/1/checkout_save
  def checkout_save

    @reserva = Reserva.find(params[:id])
    @reserva.Checkout = Checkout.new(params[:checkout])
    
    @reserva.DataSaida = DateTime.now
    
    consumos = []
    params[:consumo].each do |v,c|
      consumos.push Consumo.new(c)
    end
    @reserva.Checkout.Consumo = consumos
    
    respond_to do |format|
      if @reserva.save
        format.html { redirect_to [:admin, @reserva.Checkout], notice: 'Checkout efetuado com sucesso!' }
        format.json { render json: @reserva.Checkout, status: :created, location: @reserva.Checkout }
      else
        format.html { render action: "checkout_save" }
        format.json { render json: @reserva.Checkout.errors, status: :unprocessable_entity }
      end
    end
  end
  
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  
  before_filter :authenticate_cliente!, :only => [:nova, :create, :sucesso]

  def after_sign_in_path_for(resource)
    Rails.application.routes.url_helpers.cliente_sucesso_path
  end
  
  # GET /reservas/show/:dataEntrada/:dataSaida
  def show    
    @quartos = Quarto.all
    @quartos_livres = [];
    
    @quartos.each do |quarto|
      if !quarto.ocupado? params[:dataEntrada].to_datetime, params[:dataSaida].to_datetime
        @quartos_livres.push quarto
      end
    end
    
  end
  
  # GET /reservas/nova/:id/:dataEntrada/:dataSaida
  def nova
    @quarto = Quarto.find(params[:id])
    
    @reserva = Reserva.new({
      :DataEntrada => params[:dataEntrada].to_datetime,
      :DataSaida => params[:dataSaida].to_datetime,
      :Quarto_id => @quarto.id
      })
    
    end
  
    # POST /reservas
    # POST /reservas.json
    def create
      @reserva = Reserva.new(params[:reserva])
      @reserva.Cliente = current_cliente

      respond_to do |format|
        if @reserva.save
          format.html { redirect_to :action => "pagamento", :id => @reserva.id }
          format.json { render json: @reserva, status: :created, location: @reserva }
        else
          format.html { render json: @reserva.errors, notice: 'Ocorreu algum erro ao salvar esta reserva.' }
          format.json { render json: @reserva.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def confirma
      @reserva = Reserva.find(params[:id])
            
      if @reserva.Pagamento == nil
        @reserva.Pagamento = "50% pagos"
      end
      
      respond_to do |format|
        if @reserva.save
          
          DefaultMailer.confirma_reserva(@reserva).deliver
          
          format.html { render :layout => "login" }
          format.json { render json: @reserva, status: :created, location: @reserva }
        else
          format.html { render json: @reserva.errors, notice: 'Ocorreu algum erro ao salvar esta reserva.' }
          format.json { render json: @reserva.errors, status: :unprocessable_entity }
        end
      end
      
    end
    
    def pagamento
      @reserva = Reserva.find(params[:id])
      
      render :layout => "login"
    end
  
  end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/admin/reservas/_form.html.erb
<%= form_for [:admin, @reserva], :html => { :class => 'form-horizontal' } do |f| %>

			<div class="control-group">
			  <%= f.label :Cliente, :class => 'control-label' %>
			  <div class="controls">
					<%= collection_select(:reserva, :Cliente_id, Cliente.all, :id, :nome, {:prompt => false}) %>
			  </div>
			</div>
			<div class="control-group">
			  <%= f.label :Quarto, :class => 'control-label' %>
			  <div class="controls">
					<%= collection_select(:reserva, :Quarto_id, Quarto.all, :id, :nome, {:prompt => false}) %>
			  </div>
			</div>
      <%= f.text_field :DataEntrada, :class => 'datetimepicker' %>
      <%= f.text_field :DataSaida, :class => 'datetimepicker' %>
			<div class="control-group">
			  <%= f.label :Pagamento, :class => 'control-label' %>
			  <div class="controls">
			<%= select(:reserva, :Pagamento, ['50% pagos', 'Cancelado', 'Pendente']) %>
			  </div>
			</div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_reservas_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/reservas/checkout.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
	<h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<% if @reserva.DataEntrada > DateTime.now %>
<div class="alert alert-block">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h4>Alerta!</h4>
  Você só pode fazer o checkout em data superior a data de entrada, caso seja preciso, altere a data de entrada.
</div>
<% end %>

<dl class="dl-horizontal">
	<dt><strong><%= model_class.human_attribute_name(:Cliente_id) %>:</strong></dt>
	<dd><%= @reserva.Cliente.nome_completo %></dd>
	<dt><strong><%= model_class.human_attribute_name(:Quarto_id) %>:</strong></dt>
	<dd><%= @reserva.Quarto.nome %></dd>
	<dt><strong><%= model_class.human_attribute_name(:DataEntrada) %>:</strong></dt>
	<dd><%=l @reserva.DataEntrada, :format => :short %></dd>
	<dt><strong><%= model_class.human_attribute_name(:DataSaida) %>:</strong></dt>
	<dd><%=l @reserva.DataSaida, :format => :short %></dd>
	<dt><strong><%= model_class.human_attribute_name(:Pagamento) %>:</strong></dt>
	<dd><%= @reserva.Pagamento %></dd>
</dl>

<%= form_for :checkout, :url => { :action => "checkout_save"}, :html => { :class => 'form-horizontal' } do |f| %>

<%= f.hidden_field :cliente, :class => 'text_field', :value => @reserva.Cliente.nome_completo %>
<%= f.hidden_field :quarto, :class => 'text_field', :value => @reserva.Quarto.nome %>
<%= f.hidden_field :dataEntrada, :class => 'text_field', :value => @reserva.DataEntrada %>
<%= f.hidden_field :dataSaida, :class => 'text_field', :value =>  @reserva.DataSaida %>
<%= f.hidden_field :valor_total, :class => 'text_field', :value => 200 %>

<table class="table table-bordered consumo">
	<thead>
		<tr>
			<th style="width: 50px">Quant.</th>
			<th>Descrição</th>
			<th style="width: 200px">Valor Unit.</th>
			<th style="width: 200px">Valor Total</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				<%= @reserva.diarias %>
				<input type="hidden" id="consumo_0_qnt" name="consumo[0][qnt]" class="qnt" value="<%= @reserva.diarias %>" />		
			</td>
			<td>
				Diaria
				<input type="hidden" id="consumo_0_desc" name="consumo[0][desc]" class="desc" value="Diaria" />		
			</td>
			<td>
				<%= @reserva.Quarto.diaria.real_formatado %>
				<input type="hidden" id="consumo_0_valor" name="consumo[0][valor]" class="valor" value="<%= @reserva.Quarto.diaria %>" />		
			</td>
			<td id="total_0" class="total">
			</td>
		</tr>
	</tbody>
	<thead>
		<tr>
			<th colspan="3">Valor Total</th>
			<th id="consumo_total">
				
			</th>
		</tr>
	</thead>
</table>

<script>calcula()</script>

<div id="addProduto" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Adicionar Produto</h3>
  </div>
  <div class="modal-body">
		<div style="float:left">
			<label>Quantidade</label>
		  <input id="quantidade" class="span1" type="number" min="1" placeholder="Quantidade" style="width: 91px; margin-right:10px;">
		</div>
		<div style="float:left">
			<label>Produto</label>
			<%= select("produtos","add",Produto.all.collect {|p| [ p.nome, p.id ] }, {:prompt => false}) %>
		</div>
		<div style="clear:both"></div>
  </div>
  <div class="modal-footer">
    <a href="javascript:void(0)" data-dismiss="modal" class="btn">Fechar</a>
    <a href="javascript:void(0)" onclick="addProduto()" class="btn btn-primary">Adicionar</a>
  </div>
</div>

Pagamento
<%= select(:checkout, :tipoPagamento, ['Á vista', 'Cartão', 'Cheque']) %>

<div class="form-actions">
	<%= link_to t('.back', :default => t("helpers.links.back")), admin_reservas_path, :class => 'btn'  %>
	<%= link_to t('.edit', default: t("helpers.links.edit")), edit_admin_reserva_path(@reserva), :class => 'btn' %>

	<% if @reserva.DataEntrada < DateTime.now %>
	<button type="button" data-toggle="modal" data-target="#addProduto" class="btn btn-success">Adicionar Produto</button>
	
	<%= f.submit 'Checkout', :class => 'btn btn-primary' %>
	<% end %>
</div>

<% end %>

app/views/admin/reservas/edit.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/reservas/index.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
	<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
	<thead>
		<tr>
			<th><%= model_class.human_attribute_name(:id) %></th>
			<th><%= model_class.human_attribute_name(:Cliente_id) %></th>
			<th><%= model_class.human_attribute_name(:Quarto_id) %></th>
			<th><%= model_class.human_attribute_name(:DataEntrada) %></th>
			<th><%= model_class.human_attribute_name(:DataSaida) %></th>
			<th><%= model_class.human_attribute_name(:Pagamento) %></th>
			<th><%= model_class.human_attribute_name(:created_at) %></th>
			<th><%=t '.actions', :default => t("helpers.actions") %></th>
		</tr>
	</thead>
	<tbody>
		<% @reservas.each do |reserva| %>
		<% if DateTime.now > reserva.DataSaida %>
		<tr class="error">
		<% else if DateTime.now > reserva.DataEntrada %>
		<tr class="info">
		<% else %>
		<tr>
		<% end %>
		<% end %>
			<td><%= link_to reserva.id, admin_reserva_path(reserva) %></td>
			<td><%= reserva.Cliente.nome_completo %></td>
			<td><%= reserva.Quarto.nome %></td>
			<td><%=l reserva.DataEntrada, :format => :short %></td>
			<td><%=l reserva.DataSaida, :format => :short %></td>
			<td><%= reserva.Pagamento %></td>
			<td><%=l reserva.created_at, :format => :short %></td>
			<td>
				<%= link_to t('.checkout', :default => t("helpers.links.checkout")),
				checkout_admin_reserva_path(reserva), :class => 'btn btn-mini btn-primary' %>
				<%= link_to t('.edit', :default => t("helpers.links.edit")),
				edit_admin_reserva_path(reserva), :class => 'btn btn-mini' %>
				<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
				admin_reserva_path(reserva),
				:method => :delete,
				:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
				:class => 'btn btn-mini btn-danger' %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
new_admin_reserva_path,
:class => 'btn btn-primary' %>

app/views/admin/reservas/new.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/reservas/show.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Cliente_id) %>:</strong></dt>
  <dd><%= @reserva.Cliente_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Quarto_id) %>:</strong></dt>
  <dd><%= @reserva.Quarto_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:DataEntrada) %>:</strong></dt>
  <dd><%=l @reserva.DataEntrada, :format => :short %></dd>
  <dt><strong><%= model_class.human_attribute_name(:DataSaida) %>:</strong></dt>
  <dd><%=l @reserva.DataSaida, :format => :short %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Pagamento) %>:</strong></dt>
  <dd><%= @reserva.Pagamento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ValorDiarias) %>:</strong></dt>
  <dd><%= @reserva.valor_diarias.real_formatado %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_reservas_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_reserva_path(@reserva), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_reserva_path(@reserva),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>