config/routes.rb
Hotel::Application.routes.draw do
  
  root :to => 'pages#index'

  match '/reservas/confirma/:id' => 'reservas#confirma', :as => :confirma_reserva
  match 'admin/' => 'admin/dashboard#index', :as => :admin_home
  match '/reservas/show/:dataEntrada/:dataSaida' => 'reservas#show'
  match '/reservas/create' => 'reservas#create', :as => :create_reserva
  match '/reservas/nova/:id/:dataEntrada/:dataSaida' => 'reservas#nova', :as => :nova_reserva
  match '/clientes/sucesso' => 'clientes#sucesso', :as => :cliente_sucesso

  resources :quartos

  namespace :admin do
    resources :produtos
    resources :checkouts do
      member do
        get :imprimir
      end
    end
    resources :clientes
    resources :usuarios
    resources :flags
    resources :quartos
    resources :tipos_quartos
    resources :reservas do 
      member do
        get :checkout
        post :checkout_save
      end
    end
    
  end
  
  devise_for :usuarios, :skip => [:sessions], :controllers => { :sessions => "admin/sessions"}
  
  as :usuario do
    get 'admin/login' => 'admin/sessions#new', :as => :new_usuario_session
    post 'admin/login' => 'admin/sessions#create', :as => :usuario_session
    get 'admin/logout' => 'admin/sessions#destroy', :as => :destroy_usuario_session,
    :via => Devise.mappings[:usuario].sign_out_via
  end

  devise_for :clientes, :controllers => { :sessions => "sessions", :registrations => :registrations}
  
  as :cliente do
    get 'clientes/login' => 'sessions#new', :as => :new_cliente_session
    post 'clientes/login' => 'sessions#create', :as => :cliente_session
    get 'clientes/logout' => 'sessions#destroy', :as => :destroy_cliente_session,
    :via => Devise.mappings[:cliente].sign_out_via
  end
  
  match ':controller(/:action(/:id))(.:format)'
  

  
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  
  # GET /dashboard
  def index
    
    @t_clientes = Cliente.count
    @t_produtos = Produto.count
    @t_reservas = Reserva.count
    @t_checkouts = Checkout.count
    @t_reservas_ativas = Reserva.count(:all, :include => :Checkout, :conditions => { :checkouts => {:id => nil}} )
    
    @u_reservas = Reserva.find(:all, :order => "id desc", :limit => 5)
    
    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/views/admin/dashboard/index.html.erb
<div class="hero-unit">
	<h1>
		Bem vindo!
	</h1>
	<p>
		Painel Administrativo 
	</p>
</div>

<div class="well summary">
	<ul>
		<li>
			<a href="<%= admin_clientes_url %>"><span class="count"><%= @t_clientes %></span> Clientes</a>
		</li>
		<li>
			<a href="<%= admin_checkouts_url %>"><span class="count"><%= @t_checkouts %></span> Checkouts</a>
		</li>
		<li>
			<a href="<%= admin_reservas_url %>"><span class="count"><%= @t_reservas_ativas %></span> Reservas Ativas</a>
		</li>
		<li class="last">
			<a href="<%= admin_produtos_url %>"><span class="count"><%= @t_produtos %></span> Produtos</a>
		</li>
	</ul>
</div>

<h2>Últimas Reservas</h2>
<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>Quarto</th>
			<th>Cliente</th>
			<th>Data da Reserva</th>
			<th>Data do Registro</th>
			<th>Visualizar</th>
		</tr>
	</thead>
	<tbody>
		<% @u_reservas.each do |reserva| %>
		<tr>
			<td><%= link_to reserva.Quarto.nome, admin_quarto_path(reserva.Quarto) %></td>
			<td><%= link_to reserva.Cliente.nome_completo, admin_cliente_path(reserva.Cliente) %></td>
			<td><%=l reserva.DataEntrada %></td>
			<td><%=l reserva.created_at %></td>
			<td><%= link_to "Visualizar", admin_reserva_path(reserva) %></td>
		</tr>
		<% end %>
	</tbody>
</table>