config/routes.rb
Hotel::Application.routes.draw do
  
  root :to => 'pages#index'

  match '/reservas/confirma/:id' => 'reservas#confirma', :as => :confirma_reserva
  match 'admin/' => 'admin/dashboard#index', :as => :admin_home
  match '/reservas/show/:dataEntrada/:dataSaida' => 'reservas#show'
  match '/reservas/create' => 'reservas#create', :as => :create_reserva
  match '/reservas/nova/:id/:dataEntrada/:dataSaida' => 'reservas#nova', :as => :nova_reserva
  match '/clientes/sucesso' => 'clientes#sucesso', :as => :cliente_sucesso

  resources :quartos

  namespace :admin do
    resources :produtos
    resources :checkouts do
      member do
        get :imprimir
      end
    end
    resources :clientes
    resources :usuarios
    resources :flags
    resources :quartos
    resources :tipos_quartos
    resources :reservas do 
      member do
        get :checkout
        post :checkout_save
      end
    end
    
  end
  
  devise_for :usuarios, :skip => [:sessions], :controllers => { :sessions => "admin/sessions"}
  
  as :usuario do
    get 'admin/login' => 'admin/sessions#new', :as => :new_usuario_session
    post 'admin/login' => 'admin/sessions#create', :as => :usuario_session
    get 'admin/logout' => 'admin/sessions#destroy', :as => :destroy_usuario_session,
    :via => Devise.mappings[:usuario].sign_out_via
  end

  devise_for :clientes, :controllers => { :sessions => "sessions", :registrations => :registrations}
  
  as :cliente do
    get 'clientes/login' => 'sessions#new', :as => :new_cliente_session
    post 'clientes/login' => 'sessions#create', :as => :cliente_session
    get 'clientes/logout' => 'sessions#destroy', :as => :destroy_cliente_session,
    :via => Devise.mappings[:cliente].sign_out_via
  end
  
  match ':controller(/:action(/:id))(.:format)'
  

  
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  attr_accessible :desc, :nome, :valor
  
  usar_como_dinheiro :valor
  
  validates_presence_of :nome, :valor
  
  validates :valor, :numericality => { :greater_than => 0 }
  
  def self.search(search)
    if search
      find(:all, :conditions => ['nome LIKE :search OR desc LIKE :search OR valor LIKE :search', {:search => "%#{search}%"}])
    else
      find(:all)
    end
  end
end

app/controllers/admin/produtos_controller.rb
class Admin::ProdutosController < Admin::ApplicationController
  # GET /produtos
  # GET /produtos.json
  def index
    @pesquisa = params[:q]
    @produtos = Produto.search(@pesquisa)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produtos }
    end
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
    @produto = Produto.find(params[:id])
    @produto['valor_real'] = @produto.valor.real_formatado
    @produto['valor_decimal'] = @produto.valor.to_decimal

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/new
  # GET /produtos/new.json
  def new
    @produto = Produto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/1/edit
  def edit
    @produto = Produto.find(params[:id])
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(params[:produto])

    respond_to do |format|
      if @produto.save
        format.html { redirect_to [:admin, @produto], notice: 'Produto criado com sucesso!' }
        format.json { render json: @produto, status: :created, location: @produto }
      else
        format.html { render action: "new" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /produtos/1
  # PUT /produtos/1.json
  def update
    @produto = Produto.find(params[:id])

    respond_to do |format|
      if @produto.update_attributes(params[:produto])
        format.html { redirect_to [:admin, @produto], notice: 'Produto atualizado com sucesso!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to admin_produtos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/admin/produtos/_form.html.erb
<%= form_for [:admin,@produto], :builder => MNE::TwitterBootstrapFormBuilder::FormBuilder, :html => { :class => "form-horizontal" } do |f| %>
							
<%= f.text_field :nome %>
<%= f.text_field :desc %>
<%= f.text_field :valor %>
			
<div class="form-actions">
	<%= f.submit nil, :class => 'btn btn-primary' %>
	<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	admin_produtos_path, :class => 'btn' %>
</div>
<% end %>

app/views/admin/produtos/edit.html.erb
<%- model_class = Produto -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/produtos/index.html.erb
<%- model_class = Produto -%>
<div class="page-header">
	<form class="navbar-search pull-right" action="">
		<input type="text" class="search-query" name="q" placeholder="Procurar" value="<%= @pesquisa %>">
	</form>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:desc) %></th>
      <th><%= model_class.human_attribute_name(:valor) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= link_to produto.id, admin_produto_path(produto) %></td>
        <td><%= produto.nome %></td>
        <td><%= produto.desc %></td>
        <td><%= produto.valor.real.reais_formatado %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_produto_path(produto), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_produto_path(produto),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_produto_path,
            :class => 'btn btn-primary' %>

app/views/admin/produtos/new.html.erb
<%- model_class = Produto -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/produtos/show.html.erb
<%- model_class = Produto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @produto.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:desc) %>:</strong></dt>
  <dd><%= @produto.desc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:valor) %>:</strong></dt>
  <dd><%= @produto.valor %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_produtos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_produto_path(@produto), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_produto_path(@produto),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>